### ISSUE TITLE
Function (the hint)

### ISSUE THREAD

**Issue by chap-videos** [jaysavsani07/math-metrix#4]
Hey, your app is nice I'm new to flutter and I use your app to learn more, I think your app is perfect but one thing is missing: (the hint) a button that gives the result of the question in a window like the help one (how to play) would be really great, i'm tinkering and i'm really lost i don't even know where to start, if you can put me on the voice

**Comment by jaysavsani07** [comment]
Hi @chap-videos 
Providing a hint could be a good option, we thought for it once but didn't apply. We follow the clean architecture so you can find logic into /data/repository  folder. All the calculation games are very simple so providing a hint there means providing a direct answer (only not if we could think it in some different way). Other games like number pyramid, picture puzzle can be good start to have a hint.
