### ISSUE TITLE
firebase file

### ISSUE THREAD

**Issue by Reus-Wang168** [jaysavsani07/math-metrix#8]
Hello, after I cloned, I have an error in the firebase configuration file. Do I need to build a project with firebase on my side to initialize?

**Comment by Reus-Wang168** [comment]
Which function of firebase does this project need to use?

**Comment by jaysavsani07** [comment]
@Reus-Wang168 Yes, You just need to follow standard Firebase setup steps for Flutter.

**Comment by mehulmk** [comment]
Hi @Reus-Wang168 
Here im adding some link to setup firebase in flutter project.

1. https://medium.com/enappd/adding-firebase-to-your-flutter-app-281b8f391b47
2. With CLI https://firebase.google.com/docs/flutter/setup?platform=android

**Which function of firebase does this project need to use?**
We are using firebase crashlytics and analytics in this project. 

Its not compulsory to use firebase. you can remove firebase from project. and if you want to setup firebase then you need to change package name. bcz, current package name is already register in our account and firebase doesnt allow same package multiple times. so, its batter to remove firebase related code from the project and then try to run it. let me know if you need more help from out side.

**Comment by mehulmk** [comment]
Hi @Reus-Wang168 
We have make firebase setup as option for initial run. so, now you dont have to setup firebase to run the app. just pull the latest code and try it.
