### ISSUE TITLE
Missing file  google-services.json in the Android 

### ISSUE THREAD

**Issue by ArunChapagain** [jaysavsani07/math-metrix#9]
![image](https://github.com/jaysavsani07/math-metrix/assets/99020948/8febfbee-c024-433f-aef0-282b1a92db58)

**Comment by jaysavsani07** [comment]
Hi
You've to configure firebase from your side to make it work

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Arun Chapagain ***@***.***>
Sent: Saturday, October 7, 2023 6:17:12 PM
To: jaysavsani07/math-metrix ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jaysavsani07/math-metrix] Missing file google-services.json in the Android (Issue #9)


[image]<https://user-images.githubusercontent.com/99020948/273386831-8febfbee-c024-433f-aef0-282b1a92db58.png>

**Comment by ArunChapagain** [comment]
let me try!
